/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;


import static java.lang.Class.forName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author palla
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    
    public LogInForm() {
        initComponents();
        setTitle("ADMIN LOGIN");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        adminP2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        adminloginpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        adminlogin = new javax.swing.JTextField();
        adminloginbutton = new javax.swing.JButton();
        adminlogincancel = new javax.swing.JButton();
        adminP1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminP2.setBackground(new java.awt.Color(66, 133, 244));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("USER ID");

        adminloginpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginpassActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");

        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });

        adminloginbutton.setBackground(new java.awt.Color(153, 255, 255));
        adminloginbutton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        adminloginbutton.setText("LOG IN");
        adminloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginbuttonActionPerformed(evt);
            }
        });

        adminlogincancel.setBackground(new java.awt.Color(204, 204, 255));
        adminlogincancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        adminlogincancel.setText("CANCEL");
        adminlogincancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminlogincancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminP2Layout = new javax.swing.GroupLayout(adminP2);
        adminP2.setLayout(adminP2Layout);
        adminP2Layout.setHorizontalGroup(
            adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminP2Layout.createSequentialGroup()
                .addGroup(adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminP2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminP2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminP2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(adminloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(adminP2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(adminloginbutton)
                        .addGap(29, 29, 29)
                        .addComponent(adminlogincancel)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        adminP2Layout.setVerticalGroup(
            adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminP2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(adminP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminloginbutton)
                    .addComponent(adminlogincancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminP1.setBackground(new java.awt.Color(234, 67, 53));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/admin.jpg"))); // NOI18N

        javax.swing.GroupLayout adminP1Layout = new javax.swing.GroupLayout(adminP1);
        adminP1.setLayout(adminP1Layout);
        adminP1Layout.setHorizontalGroup(
            adminP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, Short.MAX_VALUE)
        );
        adminP1Layout.setVerticalGroup(
            adminP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminP1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed

 
                
    }//GEN-LAST:event_adminloginActionPerformed

    private void adminloginpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminloginpassActionPerformed

    private void adminloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginbuttonActionPerformed
         try {           
        String uid=adminlogin.getText();
        String pass = String.valueOf(adminloginpass.getPassword());
        DBConnect.checklogin.setString(1,uid);
        DBConnect.checklogin.setString(2,pass);
       
          ResultSet rs=DBConnect.checklogin.executeQuery();
          
            if(rs.next()){
             
            new AdminDialog().setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this,"WELCOME");
             
          
          }
          else{
              JOptionPane.showMessageDialog(this,"INVALID ID or PASSWORD");
          }
          
            
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex);
        }
        
           
    }//GEN-LAST:event_adminloginbuttonActionPerformed

    private void adminlogincancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminlogincancelActionPerformed

            
        adminlogin.setText(null);
        adminloginpass.setText(null);
        dispose();
        new main.MainPage().setVisible(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_adminlogincancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminP1;
    private javax.swing.JPanel adminP2;
    private javax.swing.JTextField adminlogin;
    private javax.swing.JButton adminloginbutton;
    private javax.swing.JButton adminlogincancel;
    private javax.swing.JPasswordField adminloginpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
